spring.application.name=clinicasocorro

# Configuraci\u00c3\u00b3n de MySQL
# spring.datasource.url=jdbc:mysql://localhost:3306/db_hospital_integrador?serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=123maic
spring.datasource.url=jdbc:mysql://mysql-clinica-socorro-integrador-2.j.aivencloud.com:19755/defaultdb?serverTimezone=UTC&useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.password=${DB_PASSWORD:123456}
 spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update para que no modifique la estructura
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
